# Generated by Django 2.1.7 on 2019-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fenster',
            old_name='fenster_width',
            new_name='window_height',
        ),
        migrations.AddField(
            model_name='fenster',
            name='window_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
