# Generated by Django 2.1.7 on 2019-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0002_auto_20190417_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='window_number',
            field=models.IntegerField(default=0),
        ),
    ]
