# Generated by Django 2.1.7 on 2019-04-18 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0003_fenster_window_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='window_scheme',
            field=models.CharField(default='1,2', max_length=1024, validators=[django.core.validators.int_list_validator]),
        ),
    ]
