# Generated by Django 2.1.7 on 2019-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0004_fenster_window_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
